### DISCUSSION TITLE
Using traf in GitHub Actions

### DISCUSSION THREAD

**Discussion by shaharkazaz** [lemonade-hq/traf#8] [Q&A] [answered]
Hi 👋 

Running `npx @traf/nx@0.0.6 affected lint --base master` locally works as expected.
I tried adding this command as part of our CI which runs on GitHub actions but it doesn't seem to work, I'm getting:
`Error: Unable to get diff for base: "master". are you using the correct base?`

I've kept the prequirements I used for NX's affected:
1. I'm fetching all the history for all branches and tags:
```
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```
2. Nx needs the SHAs to compute the diff:
```
      - name: Nx set SHAs
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
```

I would expect that the command will work given this setup.
Any ideas to what the problem might be?

As a side note I would add a GitHub action recipe since it's probably a very common use-case.
